### ISSUE TITLE
Problem when V-Sync swap interval set to 2 on high resolution displays

### ISSUE THREAD

**Issue by b-lov** [HyperspaceMadness/Mega_Bezel#3]
Hey, first of all, thanks for the awesome work!

I'm on a m2 mac, which can finally make use of vulkan shaders on the latest RA builds.

I have a 120hz display and get the smoothest gameplay when setting VSync Swap Interval to 2 in the Video>Synchronization Settings. However when using all variants of the bezel shader with this config, the FPS are being halved even one step further, so i get 30 fps instead of 60. When i set the swap interval back to 1 the FPS goes back to 60, but scrolling is slightly less smooth.
It only happens with your bezel shader, as far as I've seen. All the other shaders work fine with swap interval 2, including all the standalone crt shaders. Unfortunately i cant get quite the look i want with those. I tried to play around with all the settings, to no avail, so i'm reaching out to you here now. Would you mind helping me to find out what in the shader chain causes this?

My best solution to get a similiar smoothness right now is to keep swap interval at 1 and set the screen refresh rate to 60hz in the system settings after starting RA and reset it to 120hz after closing it, which is quite tedious.

Best regards!

**Comment by HyperspaceMadness** [comment]
Sorry for the lag I just realised I never responded to this. I'm not sure how to fix this, I would suggest asking on the forum to see if anyone has any recommendations.
