### ISSUE TITLE
Dynamic backgrounds

### ISSUE THREAD

**Issue by housello** [HyperspaceMadness/Mega_Bezel#5]
I dont't know if it is even possible but...
How about a dynamic background option, where the shader takes the background image based on loaded rom name?

**Comment by HyperspaceMadness** [comment]
This is possible with the preset wildcards feature you can read more about it here:

https://docs.libretro.com/guides/shaders/

There is also an example in this package:
https://github.com/HyperspaceMadness/HSM_Mega_Bezel_Examples/releases

You can find the example here:
HSM_Mega_Bezel_Examples/Multigame.slangp
