### ISSUE TITLE
Mega Bezel causes RetroArch to slow down

### ISSUE THREAD

**Issue by priming54** [HyperspaceMadness/Mega_Bezel#6]
When I add Mega Bezels or any bezels at all the game starts to slow down and starts to get a lot of lag, is there a way to fix this?

**Comment by HyperspaceMadness** [comment]
Hi, If it's slowing down, this is related to how much GPU power is available on the machine you are running and what the resolution of the display is. You can try some of the presets which require less GPU Power. See the readme for a chart of the presets to get an idea of the relative performance of presets. 

If you have more questions please come to the libretro forum thread and ask them! :) 

https://forums.libretro.com/t/mega-bezel-reflection-shader-feedback-and-updates/25512
