### ISSUE TITLE
DREZ as independent shader [Feature Request]

### ISSUE THREAD

**Issue by InanimateCrbnRod** [HyperspaceMadness/Mega_Bezel#8]
Would there be a way to release DRez as its own shader, without the crt emulation or bezels, so we can downsample other shader presets in retroarch? I think this would add a lot of really fun shader combo possibilities. Thanks again for this amazing pack!

**Comment by HyperspaceMadness** [comment]
It's a good idea, now that we can stack shaders in the ui. It would certainly be possible.  I'll think of how best to distribute these

**Comment by InanimateCrbnRod** [comment]
> It's a good idea, now that we can stack shaders in the ui. It would certainly be possible. I'll think of how best to distribute these

Amazing!! I don't know how difficult it would be to code, but it would be nice to have a tweakable parameter for desired resolution as opposed to different presets per resolution like it is now. Thanks again!

**Comment by HyperspaceMadness** [comment]
I agree parameters to adjust the resolution would be ideal 

However this would be an additional feature we would need to add to retroarch since you can't bind the resolution of a pass to a parameter

**Comment by HyperspaceMadness** [comment]
I added independent DREZ presets to the main retroarch shader repo, you can find them here:
`shaders/shaders_slang/downsample`

Cheers :)

**Comment by InanimateCrbnRod** [comment]
Yay! Thank you so much!
