### ISSUE TITLE
wrong path in guide

### ISSUE THREAD

**Issue by B-Nerd** [HyperspaceMadness/Mega_Bezel#9]
it should not look like this Retroarch/shaders/shaders_slang/bezel/Mega_Bezel
but this Retroarch/shaders/bezel/Mega_Bezel

**Comment by HyperspaceMadness** [comment]
I'm not sure why you are suggesting the path should be different, the `bezel/Mega_Bezel` folder is located inside the shaders_slang folder, not the shaders folder
